/**
 * Authentication Hooks
 *
 * Export all authentication-related hooks for easy importing.
 *
 * @example
 * ```tsx
 * import { useAuth, useUser, useIsAdmin } from "@/hooks";
 * ```
 */

export {
    useAuth,
    useIsAuthenticated,
    useAuthLoading,
    useAuthError,
} from "./use-auth";

export {
    useUser,
    useUserRole,
    useIsAdmin,
    useHasRole,
    type UserData,
} from "./use-user";

export {
    useGenerateTitles,
    useGenerateMetaDescription,
    useGenerateExcerpt,
    useGenerateOutline,
    useAnalyzeContent,
    useImproveText,
    useGenerateAltText,
    type ContentAnalysis,
    type WritingTone,
} from "./use-ai";

export {
    useAnalyticsDashboard,
    useTopPosts,
    useTrafficSources,
    usePostStats,
    analyticsKeys,
    type DashboardOverview,
    type TopPost,
    type TrafficSource,
    type PostStats,
} from "./use-analytics";

export {
    useAllComments,
    useApproveComment,
    useRejectComment,
    useSpamComment,
    useDeleteComment,
    commentKeys,
    type Comment,
    type CommentFilters,
} from "./use-comments";

export {
    useMediaList,
    useMediaFolders,
    useUploadMedia,
    useUpdateMedia,
    useDeleteMedia,
    useCreateFolder,
    useDeleteFolder,
    mediaKeys,
    type MediaAsset,
    type MediaFolder,
    type MediaFilters,
} from "./use-media";

export {
    useNewsletterSubscribers,
    useNewsletterStats,
    useSendNewsletter,
    useScheduleNewsletter,
    useTestNewsletter,
    useDeleteSubscriber,
    newsletterKeys,
    type NewsletterSubscriber,
    type NewsletterStats,
    type SubscriberFilters,
} from "./use-newsletter";

export {
    useDigitalProducts,
    useDigitalProduct,
    useCreateDigitalProduct,
    useUpdateDigitalProduct,
    useDeleteDigitalProduct,
    usePublishDigitalProduct,
    useArchiveDigitalProduct,
    useDigitalProductCategories,
    useDigitalProductTags,
    useCreateDigitalProductCategory,
    useUpdateDigitalProductCategory,
    useDeleteDigitalProductCategory,
    useCreateDigitalProductTag,
    useUpdateDigitalProductTag,
    useDeleteDigitalProductTag,
    digitalProductKeys,
    type DigitalProduct,
    type DigitalProductCategory,
    type DigitalProductTag,
} from "./use-digital-products";

export {
    useOrders,
    useOrder,
    useOrderStats,
    useRefundOrder,
    orderKeys,
    type Order,
    type OrderItem,
    type DownloadToken,
    type OrderFilters,
    OrderStatus,
} from "./use-orders";

export {
    usePresentations,
    usePresentation,
    useCreatePresentation,
    useUpdatePresentation,
    useDeletePresentation,
    usePresentationSlides,
    useUploadPresentation,
    useReprocessPresentation,
    useAnalyzePresentation,
    useGenerateDescription,
    useSuggestPricing,
    usePresentationStats,
    useBulkDeletePresentations,
    useBulkAnalyzePresentations,
    useUpdateSlide,
    useReorderSlides,
    useRegenerateThumbnails,
    presentationKeys,
    type Presentation,
    type SlidePreview,
    type PresentationFilters,
    type PresentationStats,
    type CreatePresentationDto,
    type UpdatePresentationDto,
    type PresentationIndustry,
    type PresentationType,
    type PresentationFileFormat,
    type PresentationAspectRatio,
    type SlideContentType,
    type ColorScheme,
} from "./use-presentations";

export {
    useSolutionDocuments,
    useSolutionDocument,
    useCreateSolutionDocument,
    useUpdateSolutionDocument,
    useDeleteSolutionDocument,
    useDocumentBundles,
    useDocumentBundle,
    useCreateBundle,
    useUpdateBundle,
    useDeleteBundle,
    useAddToBundle,
    useRemoveFromBundle,
    useDocumentUpdates,
    usePublishUpdate,
    useUploadDocument,
    useAnalyzeDocument,
    useGenerateDocumentDescription,
    useGenerateSeo,
    useGenerateToc,
    useExtractTechStack,
    useSolutionDocumentStats,
    useBulkDeleteDocuments,
    useBulkAnalyzeDocuments,
    solutionDocumentKeys,
    type SolutionDocument,
    type DocumentBundle,
    type DocumentUpdate,
    type TOCItem,
    type SolutionDocumentFilters,
    type SolutionDocumentStats,
    type DocumentBundleFilters,
    type CreateSolutionDocumentDto,
    type UpdateSolutionDocumentDto,
    type CreateDocumentBundleDto,
    type UpdateDocumentBundleDto,
    type DocumentType,
    type Domain,
    type MaturityLevel,
    type DiagramTool,
    type DocumentStatus,
    type CloudPlatform,
    type ComplianceFramework,
    type TemplateFormat,
} from "./use-solution-documents";

export {
    useWebTemplates,
    useWebTemplate,
    useCreateWebTemplate,
    useUpdateWebTemplate,
    useDeleteWebTemplate,
    usePublishWebTemplate,
    useArchiveWebTemplate,
    useTemplateLicenses,
    webTemplateKeys,
} from "./use-web-templates";

export {
    useAdminSellers,
    useAdminSeller,
    useUpdateSeller,
    useSuspendSeller,
    useReinstateSeller,
    useSellerApplications,
    useSellerApplication,
    useReviewApplication,
    useAdminPayouts,
    useProcessPayout,
    sellerAdminKeys,
} from "./use-sellers";

export {
    useReviews,
    useReview,
    useModerateReview,
    useRespondToReview,
    useReviewStats,
    useTopReviewers,
    useFlaggedReviews,
    useModerationQueue,
    useReviewAnalytics,
    useDismissReports,
    useRemoveReview,
    reviewKeys,
    type Review,
    type ReviewReport,
    type AIModerationResult,
    type ReviewStatus,
    type ReportStatus,
    type ReviewFilters,
    type ReviewStats,
    type TopReviewer,
    type ReviewAnalytics,
} from "./use-reviews";

export {
    useDownloadAnalytics,
    useDownloadLinks,
    useDownloadLogs,
    useRevokeDownloadLink,
    useAdminLicenses,
    useAdminLicense,
    useRevokeLicense,
    useSuspendLicense,
    useReactivateLicense,
    useProductUpdates,
    useProductChangelog,
    usePublishProductUpdate,
    useSendUpdateNotifications,
    usePendingNotifications,
    useSuspiciousDownloads,
    useDismissSuspiciousPattern,
    deliveryKeys,
    type DownloadLink,
    type DownloadLog,
    type License,
    type LicenseActivation,
    type ProductUpdate,
    type DownloadAnalytics,
    type SuspiciousPattern,
    type DownloadLinkFilters,
    type LicenseFilters,
} from "./use-delivery";

export {
    useCoupons,
    useCoupon,
    useCreateCoupon,
    useUpdateCoupon,
    useDeleteCoupon,
    useBulkCreateCoupons,
    useFlashSales,
    useCreateFlashSale,
    useBundleDiscounts,
    useCreateBundleDiscount,
    useLoyaltyTiers,
    useCreateLoyaltyTier,
    useUpdateLoyaltyTier,
    useDeleteLoyaltyTier,
    usePromotionAnalytics,
    promotionKeys,
    type Coupon,
    type CouponFilters,
    type CouponStatus,
    type DiscountType,
    type FlashSale,
    type FlashSaleFilters,
    type FlashSaleStatus,
    type FlashSaleProduct,
    type BundleDiscount,
    type BundleFilters,
    type BundleStatus,
    type BundleProduct,
    type LoyaltyTier,
    type PromotionAnalytics,
} from "./use-promotions";

export {
    usePlatformOverview,
    usePlatformRevenue,
    useTopProducts,
    useConversionFunnel,
    useCategoryRevenue,
    useMarketplaceTrafficSources,
    useDeviceBreakdown,
    useSellerOverview,
    useSellerRevenue,
    useProductAnalytics,
    useProductTraffic,
    useExportRevenue,
    marketplaceAnalyticsKeys,
    type Period,
    type GroupBy,
    type PlatformOverview,
    type RevenueDataPoint,
    type TopProduct,
    type FunnelStage,
    type CategoryRevenue,
    type TrafficSourceData,
    type DeviceBreakdown,
    type SellerOverview,
    type SellerRevenuePoint,
    type ProductAnalyticsData,
    type ProductTrafficData,
    type MarketplaceOverviewData,
} from "./use-marketplace-analytics";
