import { DataSource } from 'typeorm';
import { Achievement } from '../../modules/gamification/entities/achievement.entity';
import {
  AchievementCategory,
  AchievementTier,
} from '../../modules/gamification/enums/gamification.enums';

export async function seedAchievements(
  dataSource: DataSource,
): Promise<void> {
  const repo = dataSource.getRepository(Achievement);

  const achievements: Array<Partial<Achievement>> = [
    // ── BUYER Achievements ───────────────────────────────────────────
    {
      slug: 'first-purchase',
      name: 'First Steps',
      description: 'Make your first purchase',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'purchase_count', threshold: 1 },
      xpReward: 50,
      badgeColor: '#CD7F32',
      sortOrder: 1,
    },
    {
      slug: 'collector',
      name: 'Collector',
      description: 'Own 10 products in your library',
      category: AchievementCategory.COLLECTOR,
      tier: AchievementTier.SILVER,
      requirement: { type: 'owned_products', threshold: 10 },
      xpReward: 200,
      badgeColor: '#C0C0C0',
      sortOrder: 2,
    },
    {
      slug: 'power-buyer',
      name: 'Power Buyer',
      description: 'Own 25 products in your library',
      category: AchievementCategory.COLLECTOR,
      tier: AchievementTier.GOLD,
      requirement: { type: 'owned_products', threshold: 25 },
      xpReward: 500,
      badgeColor: '#FFD700',
      sortOrder: 3,
    },
    {
      slug: 'ultimate-library',
      name: 'Ultimate Library',
      description: 'Own 100 products in your library',
      category: AchievementCategory.COLLECTOR,
      tier: AchievementTier.PLATINUM,
      requirement: { type: 'owned_products', threshold: 100 },
      xpReward: 2000,
      badgeColor: '#E5E4E2',
      sortOrder: 4,
    },
    {
      slug: 'big-spender',
      name: 'Big Spender',
      description: 'Spend $500 or more in total purchases',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'total_spend', threshold: 500 },
      xpReward: 500,
      badgeColor: '#FFD700',
      sortOrder: 5,
    },
    {
      slug: 'category-explorer',
      name: 'Category Explorer',
      description: 'Buy from 5 or more different product categories',
      category: AchievementCategory.EXPLORER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'distinct_categories_purchased', threshold: 5 },
      xpReward: 200,
      badgeColor: '#C0C0C0',
      sortOrder: 6,
    },
    {
      slug: 'full-stack',
      name: 'Full Stack',
      description: 'Buy one of each product type',
      category: AchievementCategory.EXPLORER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'distinct_categories_purchased', threshold: 8 },
      xpReward: 1000,
      badgeColor: '#FFD700',
      sortOrder: 7,
    },
    {
      slug: 'bundle-master',
      name: 'Bundle Master',
      description: 'Complete 5 purchases',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'purchase_count', threshold: 5 },
      xpReward: 300,
      badgeColor: '#C0C0C0',
      sortOrder: 8,
    },
    {
      slug: 'spending-milestone-100',
      name: 'Getting Started',
      description: 'Spend $100 total on the marketplace',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'total_spend', threshold: 100 },
      xpReward: 100,
      badgeColor: '#CD7F32',
      sortOrder: 9,
    },
    {
      slug: 'spending-milestone-2000',
      name: 'Platinum Spender',
      description: 'Spend $2,000 total on the marketplace',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.PLATINUM,
      requirement: { type: 'total_spend', threshold: 2000 },
      xpReward: 1500,
      badgeColor: '#E5E4E2',
      sortOrder: 10,
    },

    // ── REVIEWER Achievements ────────────────────────────────────────
    {
      slug: 'first-review',
      name: 'First Review',
      description: 'Write your first product review',
      category: AchievementCategory.REVIEWER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'review_count', threshold: 1 },
      xpReward: 50,
      badgeColor: '#CD7F32',
      sortOrder: 20,
    },
    {
      slug: 'helpful-voice',
      name: 'Helpful Voice',
      description: 'Receive 10 helpful votes on your reviews',
      category: AchievementCategory.REVIEWER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'helpful_votes', threshold: 10 },
      xpReward: 200,
      badgeColor: '#C0C0C0',
      sortOrder: 21,
    },
    {
      slug: 'top-critic',
      name: 'Top Critic',
      description: 'Write 25 reviews',
      category: AchievementCategory.REVIEWER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'review_count', threshold: 25 },
      xpReward: 500,
      badgeColor: '#FFD700',
      sortOrder: 22,
    },
    {
      slug: 'influencer',
      name: 'Influencer',
      description: 'Receive 100 helpful votes on your reviews',
      category: AchievementCategory.REVIEWER,
      tier: AchievementTier.PLATINUM,
      requirement: { type: 'helpful_votes', threshold: 100 },
      xpReward: 1000,
      badgeColor: '#E5E4E2',
      sortOrder: 23,
    },
    {
      slug: 'five-reviews',
      name: 'Regular Reviewer',
      description: 'Write 5 reviews',
      category: AchievementCategory.REVIEWER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'review_count', threshold: 5 },
      xpReward: 150,
      badgeColor: '#CD7F32',
      sortOrder: 24,
    },

    // ── SELLER Achievements ──────────────────────────────────────────
    {
      slug: 'first-sale',
      name: 'First Sale',
      description: 'Make your first sale on the marketplace',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'sale_count', threshold: 1 },
      xpReward: 100,
      badgeColor: '#CD7F32',
      sortOrder: 30,
    },
    {
      slug: 'rising-star',
      name: 'Rising Star',
      description: 'Reach 50 total sales',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'sale_count', threshold: 50 },
      xpReward: 500,
      badgeColor: '#C0C0C0',
      sortOrder: 31,
    },
    {
      slug: 'top-seller',
      name: 'Top Seller',
      description: 'Reach 500 total sales',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'sale_count', threshold: 500 },
      xpReward: 2000,
      badgeColor: '#FFD700',
      sortOrder: 32,
    },
    {
      slug: 'revenue-milestone',
      name: 'Revenue Milestone',
      description: 'Earn $10,000 in total revenue',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'seller_revenue', threshold: 10000 },
      xpReward: 1500,
      badgeColor: '#FFD700',
      sortOrder: 33,
    },
    {
      slug: 'prolific-creator',
      name: 'Prolific Creator',
      description: 'Upload 25 products to the marketplace',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'product_count', threshold: 25 },
      xpReward: 1000,
      badgeColor: '#FFD700',
      sortOrder: 34,
    },
    {
      slug: 'first-product',
      name: 'Creator',
      description: 'Upload your first product',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'product_count', threshold: 1 },
      xpReward: 100,
      badgeColor: '#CD7F32',
      sortOrder: 35,
    },
    {
      slug: 'five-products',
      name: 'Active Creator',
      description: 'Upload 5 products to the marketplace',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'product_count', threshold: 5 },
      xpReward: 400,
      badgeColor: '#C0C0C0',
      sortOrder: 36,
    },
    {
      slug: 'revenue-1k',
      name: 'Revenue Starter',
      description: 'Earn $1,000 in total revenue',
      category: AchievementCategory.SELLER,
      tier: AchievementTier.SILVER,
      requirement: { type: 'seller_revenue', threshold: 1000 },
      xpReward: 500,
      badgeColor: '#C0C0C0',
      sortOrder: 37,
    },

    // ── COMMUNITY Achievements ───────────────────────────────────────
    {
      slug: 'streak-7',
      name: 'Week Warrior',
      description: 'Maintain a 7-day login streak',
      category: AchievementCategory.COMMUNITY,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'streak_days', threshold: 7 },
      xpReward: 100,
      badgeColor: '#CD7F32',
      sortOrder: 40,
    },
    {
      slug: 'streak-30',
      name: 'Streak Master',
      description: 'Maintain a 30-day login streak',
      category: AchievementCategory.COMMUNITY,
      tier: AchievementTier.GOLD,
      requirement: { type: 'streak_days', threshold: 30 },
      xpReward: 500,
      badgeColor: '#FFD700',
      sortOrder: 41,
    },
    {
      slug: 'streak-100',
      name: 'Centurion',
      description: 'Maintain a 100-day login streak',
      category: AchievementCategory.COMMUNITY,
      tier: AchievementTier.DIAMOND,
      requirement: { type: 'streak_days', threshold: 100 },
      xpReward: 2500,
      badgeColor: '#B9F2FF',
      sortOrder: 42,
    },
    {
      slug: 'streak-14',
      name: 'Fortnight Regular',
      description: 'Maintain a 14-day login streak',
      category: AchievementCategory.COMMUNITY,
      tier: AchievementTier.SILVER,
      requirement: { type: 'streak_days', threshold: 14 },
      xpReward: 200,
      badgeColor: '#C0C0C0',
      sortOrder: 43,
    },

    // ── SECRET Achievements ──────────────────────────────────────────
    {
      slug: 'night-owl',
      name: 'Night Owl',
      description: 'Make a purchase between midnight and 4 AM',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.BRONZE,
      requirement: { type: 'purchase_time_range', start: 0, end: 4 },
      xpReward: 75,
      badgeColor: '#1E1B4B',
      isSecret: true,
      sortOrder: 50,
    },
    {
      slug: 'dedicated-buyer',
      name: 'Dedicated Buyer',
      description: 'Complete 25 purchases',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.GOLD,
      requirement: { type: 'purchase_count', threshold: 25 },
      xpReward: 750,
      badgeColor: '#FFD700',
      sortOrder: 51,
    },
    {
      slug: 'marketplace-maven',
      name: 'Marketplace Maven',
      description: 'Complete 50 purchases — you truly love this marketplace!',
      category: AchievementCategory.BUYER,
      tier: AchievementTier.DIAMOND,
      requirement: { type: 'purchase_count', threshold: 50 },
      xpReward: 2000,
      badgeColor: '#B9F2FF',
      isSecret: true,
      sortOrder: 52,
    },
  ];

  let created = 0;
  for (const data of achievements) {
    const existing = await repo.findOne({
      where: { slug: data.slug },
    });
    if (!existing) {
      const achievement = repo.create({
        ...data,
        isSecret: data.isSecret ?? false,
        isActive: true,
      });
      await repo.save(achievement);
      created++;
    }
  }

  console.log(
    `Achievements seed: ${created} created, ${achievements.length - created} already existed`,
  );
}
